eliminating addictions
the files that depend on the operation have been inserted directly into the folder to eliminate the errors:
Error: Cannot find module './node_modules/pngjs/lib/constants'   and Error: Cannot find module './node_modules/pngjs/lib/filter'